/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ierc20Sol from './IERC20.sol/index.js';
export { IInitializableProxy__factory } from './IInitializableProxy__factory.js';
export { IPriceFeed__factory } from './IPriceFeed__factory.js';