// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "error InvalidInitialization()",
    "error NotInitializing()",
    "error OwnableInvalidOwner(address owner)",
    "error OwnableUnauthorizedAccount(address account)",
    "event AddSettler(address newSettler)",
    "event Initialized(uint64 version)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "event RemoveSettler(address oldSettler)",
    "function addSettler(address _settler)",
    "function initializeSettler(address _initOwner)",
    "function owner() view returns (address)",
    "function removeSettler(address _settler)",
    "function renounceOwnership()",
    "function settlers() view returns (address[])",
    "function transferOwnership(address newOwner)"
] as const;
