// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "error InvalidInitialization()",
    "error NotInitializing()",
    "error OwnableInvalidOwner(address owner)",
    "error OwnableUnauthorizedAccount(address account)",
    "event Initialized(uint64 version)",
    "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
    "function owner() view returns (address)",
    "function renounceOwnership()",
    "function transferOwnership(address newOwner)"
] as const;
