/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20BurnableUpgradeableSol from"./ERC20BurnableUpgradeable.sol/index.js";
export type { erc20BurnableUpgradeableSol };
import type * as erc20PermitUpgradeableSol from"./ERC20PermitUpgradeable.sol/index.js";
export type { erc20PermitUpgradeableSol };
