// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "function admin() view returns (address)",
    "function changeAdmin(address newAdmin)",
    "function implementation() view returns (address)",
    "function initializeProxy(string _description, address newAdmin, address newImplementation, bytes data) payable",
    "function proxyDescription() view returns (bytes)",
    "function upgradeToAndCall(address newImplementation, bytes data) payable"
] as const;
