/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'GoldMinter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GoldMinter__factory>
getContractFactory(name: 'Lock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Lock__factory>
getContractFactory(name: 'IERC20Exp', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20Exp__factory>
getContractFactory(name: 'IERC20Mintable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20Mintable__factory>
getContractFactory(name: 'IInitializableProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IInitializableProxy__factory>
getContractFactory(name: 'IPriceFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPriceFeed__factory>
getContractFactory(name: 'Errors', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Errors__factory>
getContractFactory(name: 'Ownable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Ownable__factory>
getContractFactory(name: 'SigLib', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SigLib__factory>
getContractFactory(name: 'WithSettler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WithSettler__factory>
getContractFactory(name: 'AGTPriceFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AGTPriceFeed__factory>
getContractFactory(name: 'AGTReserveFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AGTReserveFeed__factory>
getContractFactory(name: 'BaseFunctionsConsumer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BaseFunctionsConsumer__factory>
getContractFactory(name: 'DataFeed', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DataFeed__factory>
getContractFactory(name: 'DataFeedAggregator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DataFeedAggregator__factory>
getContractFactory(name: 'FunctionsClient', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FunctionsClient__factory>
getContractFactory(name: 'InitializableProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InitializableProxy__factory>
getContractFactory(name: 'ERC20Mock', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC20Mock__factory>
getContractFactory(name: 'GoldToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GoldToken__factory>
getContractFactory(name: 'InitializableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.InitializableERC20__factory>

  getContractAt(name: 'GoldMinter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GoldMinter>
getContractAt(name: 'Lock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Lock>
getContractAt(name: 'IERC20Exp', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20Exp>
getContractAt(name: 'IERC20Mintable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20Mintable>
getContractAt(name: 'IInitializableProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IInitializableProxy>
getContractAt(name: 'IPriceFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPriceFeed>
getContractAt(name: 'Errors', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Errors>
getContractAt(name: 'Ownable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Ownable>
getContractAt(name: 'SigLib', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SigLib>
getContractAt(name: 'WithSettler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WithSettler>
getContractAt(name: 'AGTPriceFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AGTPriceFeed>
getContractAt(name: 'AGTReserveFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AGTReserveFeed>
getContractAt(name: 'BaseFunctionsConsumer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BaseFunctionsConsumer>
getContractAt(name: 'DataFeed', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DataFeed>
getContractAt(name: 'DataFeedAggregator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DataFeedAggregator>
getContractAt(name: 'FunctionsClient', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FunctionsClient>
getContractAt(name: 'InitializableProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InitializableProxy>
getContractAt(name: 'ERC20Mock', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC20Mock>
getContractAt(name: 'GoldToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GoldToken>
getContractAt(name: 'InitializableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.InitializableERC20>

  deployContract(name: 'GoldMinter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GoldMinter>
deployContract(name: 'Lock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Lock>
deployContract(name: 'IERC20Exp', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Exp>
deployContract(name: 'IERC20Mintable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Mintable>
deployContract(name: 'IInitializableProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IInitializableProxy>
deployContract(name: 'IPriceFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPriceFeed>
deployContract(name: 'Errors', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Errors>
deployContract(name: 'Ownable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'SigLib', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SigLib>
deployContract(name: 'WithSettler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WithSettler>
deployContract(name: 'AGTPriceFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AGTPriceFeed>
deployContract(name: 'AGTReserveFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AGTReserveFeed>
deployContract(name: 'BaseFunctionsConsumer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseFunctionsConsumer>
deployContract(name: 'DataFeed', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DataFeed>
deployContract(name: 'DataFeedAggregator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DataFeedAggregator>
deployContract(name: 'FunctionsClient', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FunctionsClient>
deployContract(name: 'InitializableProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InitializableProxy>
deployContract(name: 'ERC20Mock', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20Mock>
deployContract(name: 'GoldToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GoldToken>
deployContract(name: 'InitializableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InitializableERC20>

  deployContract(name: 'GoldMinter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GoldMinter>
deployContract(name: 'Lock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Lock>
deployContract(name: 'IERC20Exp', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Exp>
deployContract(name: 'IERC20Mintable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Mintable>
deployContract(name: 'IInitializableProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IInitializableProxy>
deployContract(name: 'IPriceFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPriceFeed>
deployContract(name: 'Errors', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Errors>
deployContract(name: 'Ownable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'SigLib', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SigLib>
deployContract(name: 'WithSettler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WithSettler>
deployContract(name: 'AGTPriceFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AGTPriceFeed>
deployContract(name: 'AGTReserveFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AGTReserveFeed>
deployContract(name: 'BaseFunctionsConsumer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseFunctionsConsumer>
deployContract(name: 'DataFeed', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DataFeed>
deployContract(name: 'DataFeedAggregator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DataFeedAggregator>
deployContract(name: 'FunctionsClient', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FunctionsClient>
deployContract(name: 'InitializableProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InitializableProxy>
deployContract(name: 'ERC20Mock', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC20Mock>
deployContract(name: 'GoldToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GoldToken>
deployContract(name: 'InitializableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.InitializableERC20>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  