/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Mock__factory } from './ERC20Mock__factory.js';
export { GoldToken__factory } from './GoldToken__factory.js';
export { InitializableERC20__factory } from './InitializableERC20__factory.js';