/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from"./interfaces/index.js";
export type { interfaces };
export type { AutomationBase } from "./AutomationBase.js";
export type { AutomationCompatible } from "./AutomationCompatible.js";
