// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "error AMLBlocked()",
    "error AlreadySettled()",
    "error ExpiredSignature()",
    "error InvalidNonce()",
    "error InvalidNonceSignature()",
    "error InvalidPrice()",
    "error InvalidSignature()",
    "error Overflow()",
    "error PriceOutOfRange()",
    "error SmallAmount()",
    "error StalePrice()",
    "error Underlevel()",
    "error Underpriced()",
    "error ZeroGoldToken()",
    "error ZeroOwner()",
    "error ZeroPriceFeed()",
    "error ZeroRecipient()",
    "error ZeroUSDC()",
    "error ZeroUSDRecipient()",
    "error ZeroUSDT()"
] as const;
