// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "event Approval(address indexed owner, address indexed spender, uint256 value)",
    "event Transfer(address indexed from, address indexed to, uint256 value)",
    "function DOMAIN_SEPARATOR() view returns (bytes32)",
    "function allowance(address owner, address spender) view returns (uint256)",
    "function approve(address spender, uint256 value) returns (bool)",
    "function balanceOf(address account) view returns (uint256)",
    "function burn(uint256 value)",
    "function burnFrom(address account, uint256 amount)",
    "function decimals() view returns (uint8)",
    "function mint(address to, uint256 amount)",
    "function name() view returns (string)",
    "function nonces(address owner) view returns (uint256)",
    "function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
    "function symbol() view returns (string)",
    "function totalSupply() view returns (uint256)",
    "function transfer(address to, uint256 value) returns (bool)",
    "function transferFrom(address from, address to, uint256 value) returns (bool)"
] as const;
