// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "function decimals() pure returns (uint8)",
    "function getTokenType() pure returns (uint256)",
    "function latestAnswer() view returns (int256)",
    "function latestRound() view returns (uint256)",
    "function latestRoundData() view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound)"
] as const;
