/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Errors, ErrorsInterface } from "../../libraries/Errors.js";

  const _abi = [
  {
    "inputs": [],
    "name": "AMLBlocked",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadySettled",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ExpiredSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidNonce",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidNonceSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPrice",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidSignature",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Overflow",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PriceOutOfRange",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SmallAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StalePrice",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Underlevel",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Underpriced",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroGoldToken",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroPriceFeed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroRecipient",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroUSDC",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroUSDRecipient",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ZeroUSDT",
    "type": "error"
  }
] as const;

  const _bytecode = "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220f1539b4b179abf1cf6b96d483327810fa7cb44a3dbad157285980cd14835c83564736f6c634300081e0033";

  
      type ErrorsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ErrorsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Errors__factory extends ContractFactory {
    
      constructor(...args: ErrorsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Errors & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Errors__factory {
      return super.connect(runner) as Errors__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ErrorsInterface {
      return new Interface(_abi) as ErrorsInterface;
    }
    
    override attach(address: string | Addressable): Errors {
      return super.attach(address) as Errors;
    }
  static connect(address: string, runner?: ContractRunner | null): Errors {
      return new Contract(address, _abi, runner) as unknown as Errors;
    }
  }

  
  