/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFunctionsClient } from "./IFunctionsClient.js";
export type { IFunctionsRouter } from "./IFunctionsRouter.js";
