// this file was automatically generated by @solidstate/hardhat-abi-exporter - do not modify
export default [
    "error ERC1967InvalidAdmin(address admin)",
    "error ERC1967InvalidImplementation(address implementation)",
    "error ERC1967NonPayable()",
    "event AdminChanged(address previousAdmin, address newAdmin)",
    "event DescriptionChanged(string description)",
    "event Upgraded(address indexed implementation)",
    "function admin() view returns (address)",
    "function changeAdmin(address newAdmin)",
    "function changeDescription(string _description)",
    "function implementation() view returns (address)",
    "function initializeProxy(string _description, address newAdmin, address newImplementation, bytes data) payable",
    "function proxyDescription() view returns (string)",
    "function upgradeToAndCall(address newImplementation, bytes data) payable"
] as const;
