/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common.js";
import type {
  SigLib,
  SigLibInterface,
} from "../../../../contracts/libraries/SigLib.sol/SigLib.js";

const _abi = [
  {
    inputs: [],
    name: "InvalidSignatureLength",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a8cae07867f053ab610ce0cbe96f95ad9a3318ec6f2b2d6c5b71ed9af71954de64736f6c634300081e0033";

type SigLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SigLibConstructorParams,
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SigLib__factory extends ContractFactory {
  constructor(...args: SigLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string },
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SigLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SigLib__factory {
    return super.connect(runner) as SigLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SigLibInterface {
    return new Interface(_abi) as SigLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): SigLib {
    return new Contract(address, _abi, runner) as unknown as SigLib;
  }
}
