/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20BurnableUpgradeableSol from "./ERC20BurnableUpgradeable.sol/index.js";
export * as erc20PermitUpgradeableSol from "./ERC20PermitUpgradeable.sol/index.js";
